Controllers/UploadController.cs
using Newtonsoft.Json;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Runtime.InteropServices;
using Excel = Microsoft.Office.Interop.Excel;
using System.Reflection;
using HumanaApp.Models;
using System.Data.SqlClient;

namespace HumanaApp.Controllers
{
    public class UploadController : Controller
    {
        private readonly HumanaEntities humana;

        public UploadController()
        {
            humana = new HumanaEntities();
        }



        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            if (file != null && file.ContentLength > 0)
            {
                try
                {
                    string fileName = Path.GetFileName(file.FileName);
                    string filePath = Path.Combine(Server.MapPath("~/App_Data/Uploads"), fileName);

                    if (!Directory.Exists(Server.MapPath("~/App_Data/Uploads")))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/App_Data/Uploads"));
                    }

                    // Save the file on the server
                    file.SaveAs(filePath);

                    // Save file information to the database
                    using (var db = new HumanaEntities()) // Replace YourDbContext with your actual DbContext
                    {
                        tblExcelfile fileModel = new tblExcelfile
                        {
                            Filename = fileName,
                        };

                        db.tblExcelfiles.Add(fileModel);
                        db.SaveChanges();
                    }

                    ViewBag.Message = fileName + "File uploaded successfully!";
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "Error while uploading the file: " + ex.Message;
                }
            }
            else
            {
                ViewBag.Message = "Please select a file to upload.";
            }

            return View("Index");
        }



        public ActionResult ShowFiles()
        {
            return View();
        }


        public ActionResult GetExcelFiles()
        {
            List<string> fileNames = GetExcelFilesList();
            return Json(fileNames, JsonRequestBehavior.AllowGet);
        }




        public List<string> GetExcelFilesList()
        {
            string uploadFolderPath = Server.MapPath("~/App_Data/Uploads");
            string[] files = Directory.GetFiles(uploadFolderPath, "*.xlsx");

            List<string> fileNames = new List<string>();
            foreach (string filePath in files)
            {
                fileNames.Add(Path.GetFileName(filePath));
            }

            return fileNames;
        }

        public ActionResult ViewData(string fileName)
        {
            return View();
        }


        [HttpGet]
        public ActionResult GetExcelData(string fileName)
        {
            string filePath = Server.MapPath("~/App_Data/Uploads/") + Uri.UnescapeDataString(fileName);
            Excel.Application excelApp = null;
            Excel.Workbook workbook = null;
            try
            {
                excelApp = new Excel.Application();
                workbook = excelApp.Workbooks.Open(filePath);
                Excel.Worksheet worksheet = (Excel.Worksheet)workbook.Sheets[1]; // Accessing the first sheet
                List<Dictionary<string, string>> excelData = new List<Dictionary<string, string>>();
                for (int row = 2; row <= worksheet.UsedRange.Rows.Count; row++) // Assuming data starts from row 2
                {
                    Dictionary<string, string> rowData = new Dictionary<string, string>();
                    for (int col = 1; col <= worksheet.UsedRange.Columns.Count; col++)
                    {
                        var columnNameRange = (Excel.Range)worksheet.Cells[1, col];
                        var cellValueRange = (Excel.Range)worksheet.Cells[row, col];

                        string columnName = columnNameRange.Value != null ? columnNameRange.Value.ToString() : "";
                        string cellValue = cellValueRange.Value != null ? cellValueRange.Value.ToString() : "";


                        rowData[columnName] = cellValue;
                    }
                    excelData.Add(rowData);
                }
                return Json(excelData, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { error = "An error occurred while loading Excel data." });
            }
            finally
            {
                if (workbook != null)
                    workbook.Close(false, Missing.Value, Missing.Value);



                if (excelApp != null)
                {
                    excelApp.Quit();
                    Marshal.ReleaseComObject(excelApp);
                }
            }
        }
        public ActionResult LoadData(string fileName)
        {
            string filePath = Server.MapPath("~/App_Data/Uploads/") + Uri.UnescapeDataString(fileName);
            List<List<string>> excelData = new List<List<string>>();
            List<string> columnNames = new List<string>();

            using (var package = new ExcelPackage(new FileInfo(filePath)))
            {
                var worksheet = package.Workbook.Worksheets[0];

                // Read column names from the first row
                for (int col = 1; col <= worksheet.Dimension.End.Column; col++)
                {
                    columnNames.Add(worksheet.Cells[1, col].Value.ToString());
                }

                // Create a DbContext instance (replace YourDbContext with your actual DbContext)
                using (var db = new HumanaEntities())
                {
                    var names = db.tblemployees.Select(x => x.SS_ID).ToList();
                    ViewBag.NameList = new SelectList(names);

                    // Start reading data from the second row
                    for (int row = 2; row <= worksheet.Dimension.End.Row; row++)
                    {
                        var rowData = new List<string>();
                        for (int col = 1; col <= worksheet.Dimension.End.Column; col++)
                        {
                            var cellValue = worksheet.Cells[row, col].Value;
                            rowData.Add(cellValue != null ? cellValue.ToString() : null);
                        }

                        // Create an instance of tblClaimsdata and populate its properties
                        var dataToSave = new tblClaimsdata
                        {
                            ProcessDate = DateTime.TryParse(rowData[0], out var processDateValue) ? (DateTime?)processDateValue : null,
                            AuditID = rowData[1],
                            ProcessorName = rowData[2],
                            BatchNo = rowData[3],
                            Leads = rowData[4],
                            ClientID = rowData[5],
                            TotalChargeAmount = decimal.TryParse(rowData[6], out var totalChargeAmountValue) ? (decimal?)totalChargeAmountValue : null,
                            TotalPaidAmount = decimal.TryParse(rowData[7], out var totalPaidAmountValue) ? (decimal?)totalPaidAmountValue : null,
                            Claimnumber = rowData[8],
                            OriginalCorrectedClaim = rowData[9],
                            Auditor = rowData[10],
                            AuditDate = DateTime.TryParse(rowData[11], out var auditDateValue) ? (DateTime?)auditDateValue : null,
                            IHT_nonIHT = bool.TryParse(rowData[12], out var ihtNonIhtValue) ? (bool?)ihtNonIhtValue : null,
                            ErrorComment = rowData[13],
                            ErrorType = rowData[14],
                            OverUnderPayment = rowData[15],
                            ErrorCode = rowData[16],
                            ErrorCategory = rowData[17],
                            ErrorSubCategory = rowData[18],
                            CorrectionStatus = rowData[19],
                            RebuttalComment = rowData[20],
                            AuditorAgreeDisagreeonRebuttal = rowData[21],
                            Auditorcommentifdisagree = rowData[22],
                            AssignName = rowData[23],
                            Date = DateTime.Now,
                            Comments = rowData[25],
                            Status = rowData[26],

                            // Add mappings for other properties
                        };

                        // Add the data to the DbContext and save changes to the database
                        db.tblClaimsdatas.Add(dataToSave);
                    }

                    db.SaveChanges();
                }
            }

            ViewBag.ColumnNames = columnNames;
            return View(excelData);
        }





        public JsonResult DeleteExcelFile(string fileName)
        {
            try
            {
                string filePath = Server.MapPath("~/App_Data/Uploads/") + Uri.UnescapeDataString(fileName); // Replace with the actual file path

                // Check if the file exists and delete it
                if (System.IO.File.Exists(filePath))
                {
                    System.IO.File.Delete(filePath);

                    // Delete the associated data from the database
                    using (var db = new HumanaEntities()) // Replace YourDbContext with your actual DbContext
                    {

Views/Upload/GetAuditData.cshtml
@model  List<HumanaApp.Models.tblClaimsdata>
@{
    ViewBag.Title = "GetAuditData";
}


<!-- Include Select2 CSS and JS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

<div class="container py-3" style="margin-top:30px;">
    <div class="btn-group mr-6 position-absolute top-right" role="group" aria-label="Second group">
        <button type="button" class=" btn btn-success btn-lg " data-toggle="modal" data-target="#exampleModal"> Assign</button>
        <button type="button" class=" btn btn-danger btn-lg " id="redirectButton" style="margin-left : 20px">Back to File List</button>
    </div>
    <table id="fileTable" style="margin-top:10px;">
        <thead>
            <tr>
                <th><input type="checkbox" id="selectAllCheckbox"></th>
                <th>Id</th>
                <th>ProcessDate</th>
                <th>AuditID</th>
                <th>ProcessorName</th>
                <th>BatchNo</th>
                <th>Leads</th>
                <th>ClientID</th>
                <th>TotalChargeAmount</th>
                <th>TotalPaidAmount</th>
                <th>Claimnumber</th>
                <th>OriginalCorrectedClaim</th>
                <th>Auditor</th>
                <th>AuditDate</th>
                <th>IHT_nonIHT</th>
                <th>ErrorComment</th>
                <th>ErrorType</th>
                <th>OverUnderPayment</th>
                <th>ErrorCode</th>
                <th>ErrorCategory</th>
                <th>ErrorSubCategory</th>
                <th>CorrectionStatus</th>
                <th>RebuttalComment</th>
                <th>AuditorAgreeDisagreeonRebuttal</th>
                <th>Auditorcommentifdisagree</th>
                <th>AssignName</th>
                <th>Date</th>
                <th>Comments</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var row in Model)
            {
                <tr>
                    <td><input type="checkbox" class="row-checkbox"></td>
                    <td>@row.Id</td>
                    <td>@row.ProcessDate</td>
                    <td>@row.AuditID</td>
                    <td>@row.ProcessorName</td>
                    <td>@row.BatchNo</td>
                    <td>@row.Leads</td>
                    <td>@row.ClientID</td>
                    <td>@row.TotalChargeAmount</td>
                    <td>@row.TotalPaidAmount</td>
                    <td>@row.Claimnumber</td>
                    <td>@row.OriginalCorrectedClaim</td>
                    <td>@row.Auditor</td>
                    <td>@row.AuditDate</td>
                    <td>@row.ErrorComment</td>
                    <td>@row.ErrorType</td>
                    <td>@row.OverUnderPayment</td>
                    <td>@row.ErrorCode</td>
                    <td>@row.ErrorCategory</td>
                    <td>@row.ErrorSubCategory</td>
                    <td>@row.CorrectionStatus</td>
                    <td>@row.RebuttalComment</td>
                    <td>@row.OverUnderPayment</td>
                    <td>@row.AuditorAgreeDisagreeonRebuttal</td>
                    <td>@row.Auditorcommentifdisagree</td>
                    <td>@row.AssignName</td>
                    <td>@row.Date</td>
                    <td>@row.Comments</td>
                    <td>@row.Status</td>
                </tr>
            }
        </tbody>
    </table>
 
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Assign Manager</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" action="@Url.Action("AssignData", "Upload")">
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <input type="text" class="form-control" id="selectedIds" name="selectedIds">
                                @*<input type="text" id="selectedIds" name="selectedIds" disabled />*@
                                <label for="assignName" class="form-label"> Assign Person</label>
                                <input type="text" class="form-control" id="assignName" name="assignName" placeholder="Assign Person">
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="form-group">
                                <label for="comment" class="form-label">Comment</label>
                                <textarea class="form-control" id="comment" name="comment" rows="3" placeholder="Write Something......." style="width:800px;"></textarea>
                            </div>
                        </div>
                        <button type="submit">Assign</button>
                    </form>

                </div>
                <div class="modal-footer">

                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save</button>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts {
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/CSS/Upload.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.7.0.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(function () {
            $('#fileTable').DataTable({
                scrollX: true,
                scrollY: true,
                autoWidth: true,
                select: {
                    style: 'multi', // 'single', 'multi', or 'os'
                },
                // Other DataTable options here
            });
        });
    </script>
  
   <script>
            $(document).ready(function () {
                // Select or deselect all checkboxes when the "Select All" checkbox is clicked
                $('#selectAllCheckbox').change(function () {
                    var isChecked = $(this).is(':checked');
                    $('.row-checkbox').prop('checked', isChecked);
                    updateSelectedRowsData();
                });

                // Update the "Select All" checkbox state based on row checkboxes
                $('.row-checkbox').change(function () {
                    var allCheckboxes = $('.row-checkbox');
                    var isChecked = allCheckboxes.length === allCheckboxes.filter(':checked').length;
                    $('#selectAllCheckbox').prop('checked', isChecked);
                    updateSelectedRowsData();
                });

                function updateSelectedRowsData() {
                    var selectedIds = [];
                    $('.row-checkbox:checked').each(function () {
                        var id = $(this).closest('tr').find('td:eq(1)').text(); // Extract the ID from the second column (index 1)
                        selectedIds.push(id.trim()); // Trim any leading/trailing whitespace
                    });

                    console.log('Selected IDs:', selectedIds); // Log the selected IDs

                    if (selectedIds.length > 0) {
                        // Join the IDs with commas and set the value in the input field
                        document.getElementById("selectedIds").value = selectedIds.join(',');
                    } else {
                        // If no checkboxes are selected, clear the input field
                        document.getElementById("selectedIds").value = "";
                    }
                }
            });
        </script>

    
   
    <script type="text/javascript">

        $(document).ready(function () {

            $("#btnShow").click(function () {

                $('#SampleModal').modal('show');

            });

        });

    </script>0
    <script>
        $(function () {
            $("#datepicker").datepicker();
        });
    </script>
    <script>
    document.getElementById("redirectButton").addEventListener("click", function () {
        var redirectToUrl = '@Url.Action("Index", "Upload")'; // Adjust controller and action names as needed
        window.location.href = redirectToUrl; // Redirect to the generated URL
    });
    </script>
  

}

Views/Upload/LoadData.cshtml
@model List<List<string>>

<!-- Include Select2 CSS and JS -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

<div class="container py-3" style="margin-top:30px;">
    <div class="btn-group mr-6 position-absolute top-right" role="group" aria-label="Second group">
        @*<button type="button" class="btn btn-secondary">5</button>
            <button type="button" class="btn btn-secondary">6</button>*@
        <button type="button" class=" btn btn-success btn-lg " data-toggle="modal" data-target="#exampleModal"> Assign</button>
        <button type="button" class=" btn btn-danger btn-lg " id="redirectButton">Back to File List</button>
    </div>
    <table id="fileTable" style="margin-top:10px;">
        <thead>
            <tr>

                <th>
                    <input type="checkbox" id="selectAllCheckbox">
                </th>
                @foreach (var columnName in ViewBag.ColumnNames)
                {
                    <th>@columnName</th>
                }
            </tr>
        </thead>
        <tbody>
            @foreach (var row in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" class="row-checkbox">
                    </td>
                    @foreach (var cell in row)
                    {
                        <td>@cell</td>
                    }
                </tr>
            }
        </tbody>
    </table>
    @*<div class="btn-group mr-2" role="group" aria-label="Second group">
            <button type="button" class=" btn btn-success btn-lg btn-block" data-toggle="modal" data-target="#exampleModal">
                Assign
            </button>
            <button type="button" class=" btn btn-danger btn-lg btn-block">
                Back to File List
            </button>
        </div>*@

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Assign Manager</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                @*<div class="form-group ">
                                        <label for="inputState">State</label>
                                        <select id="inputState" class="form-control">
                                            <option selected>Choose...</option>
                                            <option>...</option>
                                        </select>
                                    </div>*@
                                <label for="exampleFormControlInput1" class="form-label"> Assign Person</label>
                                <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="Assign Person">0
                                @Html.DropDownList("SelectedName", ViewBag.NameList as SelectList, "Select a Name", new { @class = "form-control select2" })

                                @*<label for="inputEmail4">Email</label>
                                    <input type="email" class="form-control" id="inputEmail4" placeholder="Email">*@
                            </div>

                            <div class="form-group col-md-6">
                                <label for="SelectedDate">Select a Date:</label>
                                <input type="text" id="datepicker" name="SelectedDate" class="form-control" />
                                @*<label for="inputPassword4">Password</label>
                                    <input type="password" class="form-control" id="inputPassword4" placeholder="Password">*@

                            </div>
                        </div>
                        <div class="form-row ">
                            <div class="form-group ">
                                <label for="exampleFormControlTextarea1" class="form-label">Comment</label>
                                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Write Something......." style="width:800px;"></textarea>
                            </div>
                        </div>



                    </form>
                    <!--<div class="mb-6">
                        <label for="exampleFormControlInput1" class="form-label"> Assign Person</label>
                        <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="Assign Person">
                    </div>

                    <div class="mb-6">
                        <div class="form-group">
                            <label for="SelectedDate">Select a Date:</label>
                            <input type="text" id="datepicker" name="SelectedDate" class="form-control" />
                        </div>

                    </div>-->
                    @*<div class="mb-3">
                            <label for="exampleFormControlTextarea1" class="form-label">Select</label>
                            <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example">
                                <option selected>Open this select menu</option>
                                <option value="1">One</option>
                                <option value="2">Two</option>
                                <option value="3">Three</option>
                            </select>
                        </div>*@
                    <!--<div class="mb-6">
                        <label for="exampleFormControlTextarea1" class="form-label">Comment</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Write Something......."></textarea>
                    </div>-->

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save</button>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts {
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/CSS/Upload.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.7.0.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(function () {
            $('#fileTable').DataTable({
                scrollX: true,
                scrollY: true,
                autoWidth: true,
                select: {
                    style: 'multi', // 'single', 'multi', or 'os'
                },
                // Other DataTable options here
            });
        });
    </script>
    <script>
        $(document).ready(function () {
            // Select or deselect all checkboxes when the "Select All" checkbox is clicked
            $('#selectAllCheckbox').change(function () {
                var isChecked = $(this).is(':checked');
                $('.row-checkbox').prop('checked', isChecked);
                updateSelectedRowsData();
            });

            // Update the "Select All" checkbox state based on row checkboxes
            $('.row-checkbox').change(function () {
                var allCheckboxes = $('.row-checkbox');
                var isChecked = allCheckboxes.length === allCheckboxes.filter(':checked').length;
                $('#selectAllCheckbox').prop('checked', isChecked);
                updateSelectedRowsData();
            });

            function updateSelectedRowsData() {
                var selectedData = [];
                $('.row-checkbox:checked').each(function () {
                    var rowData = [];
                    $(this).closest('tr').find('td').each(function () {
                        rowData.push($(this).text());
                    });
                    selectedData.push(rowData);
                });

                // Now, selectedData contains an array of arrays, each representing a selected row's data
                console.log('Selected Rows Data:', selectedData);

                // You can perform any additional actions or processing with the selected data here
            }

        });
    </script>

    <script type="text/javascript">

        $(document).ready(function () {

            $("#btnShow").click(function () {

                $('#SampleModal').modal('show');

            });

        });

    </script>
    <script>
        $(function () {
            $("#datepicker").datepicker();
        });
    </script>
    <script>
    document.getElementById("redirectButton").addEventListener("click", function () {
        var redirectToUrl = '@Url.Action("Index", "Upload")'; // Adjust controller and action names as needed
        window.location.href = redirectToUrl; // Redirect to the generated URL
    });
    </script>
    <script>
        $(document).ready(function () {
            $('.select2').select2({
                placeholder: "Select a Name",
                allowClear: true // Option to clear the selection
            });
        });
    </script>
}